PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?disease ?covid19_disease
WHERE {
  VALUES ?covid19_disease {obo:DOID_0080600} .
  ?disease rdfs:seeAlso ?covid19_disease .
}
