PREFIX : <http://rdf.glycoinfo.org/SugarBind/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>

SELECT distinct ?structure
WHERE {
  ?structure a glycan:Saccharide .
}
